Update matplotlib (#1984)
* Updating to matplotlib 3.3

* Print which files are being tested.

* matplotlib no longer accepts loc of best for legend.

* Regolding images for matplotlib 3.3 update.

* Python 3.9 __file__ gives the absolute path, but relative is needed.

* xarray 0.20 throwing exception

xarray/backends/plugins.py", line 105, in list_engines
    entrypoints = entry_points().get("xarray.backends", ())
AttributeError: 'EntryPoints' object has no attribute 'get'